
package com.vidyo.portal.guest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T16:43:30.809+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "AllLinesInUseFault", targetNamespace = "http://portal.vidyo.com/guest")
public class AllLinesInUseFault_Exception extends Exception {
    
    private com.vidyo.portal.guest.AllLinesInUseFault allLinesInUseFault;

    public AllLinesInUseFault_Exception() {
        super();
    }
    
    public AllLinesInUseFault_Exception(String message) {
        super(message);
    }
    
    public AllLinesInUseFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AllLinesInUseFault_Exception(String message, com.vidyo.portal.guest.AllLinesInUseFault allLinesInUseFault) {
        super(message);
        this.allLinesInUseFault = allLinesInUseFault;
    }

    public AllLinesInUseFault_Exception(String message, com.vidyo.portal.guest.AllLinesInUseFault allLinesInUseFault, Throwable cause) {
        super(message, cause);
        this.allLinesInUseFault = allLinesInUseFault;
    }

    public com.vidyo.portal.guest.AllLinesInUseFault getFaultInfo() {
        return this.allLinesInUseFault;
    }
}
