
package com.vidyo.portal.guest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T16:43:30.809+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "ConferenceLockedFault", targetNamespace = "http://portal.vidyo.com/guest")
public class ConferenceLockedFault_Exception extends Exception {
    
    private com.vidyo.portal.guest.ConferenceLockedFault conferenceLockedFault;

    public ConferenceLockedFault_Exception() {
        super();
    }
    
    public ConferenceLockedFault_Exception(String message) {
        super(message);
    }
    
    public ConferenceLockedFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ConferenceLockedFault_Exception(String message, com.vidyo.portal.guest.ConferenceLockedFault conferenceLockedFault) {
        super(message);
        this.conferenceLockedFault = conferenceLockedFault;
    }

    public ConferenceLockedFault_Exception(String message, com.vidyo.portal.guest.ConferenceLockedFault conferenceLockedFault, Throwable cause) {
        super(message, cause);
        this.conferenceLockedFault = conferenceLockedFault;
    }

    public com.vidyo.portal.guest.ConferenceLockedFault getFaultInfo() {
        return this.conferenceLockedFault;
    }
}
