
package com.vidyo.portal.guest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T16:43:30.804+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "InvalidArgumentFault", targetNamespace = "http://portal.vidyo.com/guest")
public class InvalidArgumentFault_Exception extends Exception {
    
    private com.vidyo.portal.guest.InvalidArgumentFault invalidArgumentFault;

    public InvalidArgumentFault_Exception() {
        super();
    }
    
    public InvalidArgumentFault_Exception(String message) {
        super(message);
    }
    
    public InvalidArgumentFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidArgumentFault_Exception(String message, com.vidyo.portal.guest.InvalidArgumentFault invalidArgumentFault) {
        super(message);
        this.invalidArgumentFault = invalidArgumentFault;
    }

    public InvalidArgumentFault_Exception(String message, com.vidyo.portal.guest.InvalidArgumentFault invalidArgumentFault, Throwable cause) {
        super(message, cause);
        this.invalidArgumentFault = invalidArgumentFault;
    }

    public com.vidyo.portal.guest.InvalidArgumentFault getFaultInfo() {
        return this.invalidArgumentFault;
    }
}
