
package com.vidyo.portal.guest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T16:43:30.799+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "RoomIsFullFault", targetNamespace = "http://portal.vidyo.com/guest")
public class RoomIsFullFault_Exception extends Exception {
    
    private com.vidyo.portal.guest.RoomIsFullFault roomIsFullFault;

    public RoomIsFullFault_Exception() {
        super();
    }
    
    public RoomIsFullFault_Exception(String message) {
        super(message);
    }
    
    public RoomIsFullFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RoomIsFullFault_Exception(String message, com.vidyo.portal.guest.RoomIsFullFault roomIsFullFault) {
        super(message);
        this.roomIsFullFault = roomIsFullFault;
    }

    public RoomIsFullFault_Exception(String message, com.vidyo.portal.guest.RoomIsFullFault roomIsFullFault, Throwable cause) {
        super(message, cause);
        this.roomIsFullFault = roomIsFullFault;
    }

    public com.vidyo.portal.guest.RoomIsFullFault getFaultInfo() {
        return this.roomIsFullFault;
    }
}
