
package com.vidyo.portal.guest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T16:43:30.814+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "WrongPinFault", targetNamespace = "http://portal.vidyo.com/guest")
public class WrongPinFault_Exception extends Exception {
    
    private com.vidyo.portal.guest.WrongPinFault wrongPinFault;

    public WrongPinFault_Exception() {
        super();
    }
    
    public WrongPinFault_Exception(String message) {
        super(message);
    }
    
    public WrongPinFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WrongPinFault_Exception(String message, com.vidyo.portal.guest.WrongPinFault wrongPinFault) {
        super(message);
        this.wrongPinFault = wrongPinFault;
    }

    public WrongPinFault_Exception(String message, com.vidyo.portal.guest.WrongPinFault wrongPinFault, Throwable cause) {
        super(message, cause);
        this.wrongPinFault = wrongPinFault;
    }

    public com.vidyo.portal.guest.WrongPinFault getFaultInfo() {
        return this.wrongPinFault;
    }
}
