
package com.vidyo.portal.user.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:33:17.617+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "ControlMeetingFault", targetNamespace = "http://portal.vidyo.com/user/v1_1")
public class ControlMeetingFault_Exception extends Exception {
    
    private com.vidyo.portal.user.v1_1.ControlMeetingFault controlMeetingFault;

    public ControlMeetingFault_Exception() {
        super();
    }
    
    public ControlMeetingFault_Exception(String message) {
        super(message);
    }
    
    public ControlMeetingFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ControlMeetingFault_Exception(String message, com.vidyo.portal.user.v1_1.ControlMeetingFault controlMeetingFault) {
        super(message);
        this.controlMeetingFault = controlMeetingFault;
    }

    public ControlMeetingFault_Exception(String message, com.vidyo.portal.user.v1_1.ControlMeetingFault controlMeetingFault, Throwable cause) {
        super(message, cause);
        this.controlMeetingFault = controlMeetingFault;
    }

    public com.vidyo.portal.user.v1_1.ControlMeetingFault getFaultInfo() {
        return this.controlMeetingFault;
    }
}
