
package com.vidyo.portal.user.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:33:17.617+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "ResourceNotAvailableFault", targetNamespace = "http://portal.vidyo.com/user/v1_1")
public class ResourceNotAvailableFault_Exception extends Exception {
    
    private com.vidyo.portal.user.v1_1.ResourceNotAvailableFault resourceNotAvailableFault;

    public ResourceNotAvailableFault_Exception() {
        super();
    }
    
    public ResourceNotAvailableFault_Exception(String message) {
        super(message);
    }
    
    public ResourceNotAvailableFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceNotAvailableFault_Exception(String message, com.vidyo.portal.user.v1_1.ResourceNotAvailableFault resourceNotAvailableFault) {
        super(message);
        this.resourceNotAvailableFault = resourceNotAvailableFault;
    }

    public ResourceNotAvailableFault_Exception(String message, com.vidyo.portal.user.v1_1.ResourceNotAvailableFault resourceNotAvailableFault, Throwable cause) {
        super(message, cause);
        this.resourceNotAvailableFault = resourceNotAvailableFault;
    }

    public com.vidyo.portal.user.v1_1.ResourceNotAvailableFault getFaultInfo() {
        return this.resourceNotAvailableFault;
    }
}
