
package com.vidyo.portal.user.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:33:17.612+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "SeatLicenseExpiredFault", targetNamespace = "http://portal.vidyo.com/user/v1_1")
public class SeatLicenseExpiredFault_Exception extends Exception {
    
    private com.vidyo.portal.user.v1_1.SeatLicenseExpiredFault seatLicenseExpiredFault;

    public SeatLicenseExpiredFault_Exception() {
        super();
    }
    
    public SeatLicenseExpiredFault_Exception(String message) {
        super(message);
    }
    
    public SeatLicenseExpiredFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SeatLicenseExpiredFault_Exception(String message, com.vidyo.portal.user.v1_1.SeatLicenseExpiredFault seatLicenseExpiredFault) {
        super(message);
        this.seatLicenseExpiredFault = seatLicenseExpiredFault;
    }

    public SeatLicenseExpiredFault_Exception(String message, com.vidyo.portal.user.v1_1.SeatLicenseExpiredFault seatLicenseExpiredFault, Throwable cause) {
        super(message, cause);
        this.seatLicenseExpiredFault = seatLicenseExpiredFault;
    }

    public com.vidyo.portal.user.v1_1.SeatLicenseExpiredFault getFaultInfo() {
        return this.seatLicenseExpiredFault;
    }
}
