
package com.vidyo.portal.superapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-04-21T14:11:43.718+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "IncorrectIpcAccessLevelFault", targetNamespace = "http://portal.vidyo.com/superapi/")
public class IncorrectIpcAccessLevelFault_Exception extends Exception {
    
    private com.vidyo.portal.superapi.IncorrectIpcAccessLevelFault incorrectIpcAccessLevelFault;

    public IncorrectIpcAccessLevelFault_Exception() {
        super();
    }
    
    public IncorrectIpcAccessLevelFault_Exception(String message) {
        super(message);
    }
    
    public IncorrectIpcAccessLevelFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IncorrectIpcAccessLevelFault_Exception(String message, com.vidyo.portal.superapi.IncorrectIpcAccessLevelFault incorrectIpcAccessLevelFault) {
        super(message);
        this.incorrectIpcAccessLevelFault = incorrectIpcAccessLevelFault;
    }

    public IncorrectIpcAccessLevelFault_Exception(String message, com.vidyo.portal.superapi.IncorrectIpcAccessLevelFault incorrectIpcAccessLevelFault, Throwable cause) {
        super(message, cause);
        this.incorrectIpcAccessLevelFault = incorrectIpcAccessLevelFault;
    }

    public com.vidyo.portal.superapi.IncorrectIpcAccessLevelFault getFaultInfo() {
        return this.incorrectIpcAccessLevelFault;
    }
}
