
package com.vidyo.portal.superapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-04-21T14:11:44.271+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "InvalidArgumentFault", targetNamespace = "http://portal.vidyo.com/superapi/")
public class InvalidArgumentFault_Exception extends Exception {
    
    private com.vidyo.portal.superapi.InvalidArgumentFault invalidArgumentFault;

    public InvalidArgumentFault_Exception() {
        super();
    }
    
    public InvalidArgumentFault_Exception(String message) {
        super(message);
    }
    
    public InvalidArgumentFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidArgumentFault_Exception(String message, com.vidyo.portal.superapi.InvalidArgumentFault invalidArgumentFault) {
        super(message);
        this.invalidArgumentFault = invalidArgumentFault;
    }

    public InvalidArgumentFault_Exception(String message, com.vidyo.portal.superapi.InvalidArgumentFault invalidArgumentFault, Throwable cause) {
        super(message, cause);
        this.invalidArgumentFault = invalidArgumentFault;
    }

    public com.vidyo.portal.superapi.InvalidArgumentFault getFaultInfo() {
        return this.invalidArgumentFault;
    }
}
