
package com.vidyo.portal.superapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-04-21T14:11:44.022+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "InvalidTenantFault", targetNamespace = "http://portal.vidyo.com/superapi/")
public class InvalidTenantFault_Exception extends Exception {
    
    private com.vidyo.portal.superapi.InvalidTenantFault invalidTenantFault;

    public InvalidTenantFault_Exception() {
        super();
    }
    
    public InvalidTenantFault_Exception(String message) {
        super(message);
    }
    
    public InvalidTenantFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidTenantFault_Exception(String message, com.vidyo.portal.superapi.InvalidTenantFault invalidTenantFault) {
        super(message);
        this.invalidTenantFault = invalidTenantFault;
    }

    public InvalidTenantFault_Exception(String message, com.vidyo.portal.superapi.InvalidTenantFault invalidTenantFault, Throwable cause) {
        super(message, cause);
        this.invalidTenantFault = invalidTenantFault;
    }

    public com.vidyo.portal.superapi.InvalidTenantFault getFaultInfo() {
        return this.invalidTenantFault;
    }
}
