
package com.vidyo.portal.superapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-04-21T14:11:45.159+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "MissingArgumentFault", targetNamespace = "http://portal.vidyo.com/superapi/")
public class MissingArgumentFault_Exception extends Exception {
    
    private com.vidyo.portal.superapi.MissingArgumentFault missingArgumentFault;

    public MissingArgumentFault_Exception() {
        super();
    }
    
    public MissingArgumentFault_Exception(String message) {
        super(message);
    }
    
    public MissingArgumentFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MissingArgumentFault_Exception(String message, com.vidyo.portal.superapi.MissingArgumentFault missingArgumentFault) {
        super(message);
        this.missingArgumentFault = missingArgumentFault;
    }

    public MissingArgumentFault_Exception(String message, com.vidyo.portal.superapi.MissingArgumentFault missingArgumentFault, Throwable cause) {
        super(message, cause);
        this.missingArgumentFault = missingArgumentFault;
    }

    public com.vidyo.portal.superapi.MissingArgumentFault getFaultInfo() {
        return this.missingArgumentFault;
    }
}
