
package com.vidyo.portal.superapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-04-21T14:11:44.493+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "NotAuthorizedFault", targetNamespace = "http://portal.vidyo.com/superapi/")
public class NotAuthorizedFault_Exception extends Exception {
    
    private com.vidyo.portal.superapi.NotAuthorizedFault notAuthorizedFault;

    public NotAuthorizedFault_Exception() {
        super();
    }
    
    public NotAuthorizedFault_Exception(String message) {
        super(message);
    }
    
    public NotAuthorizedFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotAuthorizedFault_Exception(String message, com.vidyo.portal.superapi.NotAuthorizedFault notAuthorizedFault) {
        super(message);
        this.notAuthorizedFault = notAuthorizedFault;
    }

    public NotAuthorizedFault_Exception(String message, com.vidyo.portal.superapi.NotAuthorizedFault notAuthorizedFault, Throwable cause) {
        super(message, cause);
        this.notAuthorizedFault = notAuthorizedFault;
    }

    public com.vidyo.portal.superapi.NotAuthorizedFault getFaultInfo() {
        return this.notAuthorizedFault;
    }
}
