
package com.vidyo.portal.superapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-04-21T14:11:44.718+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "NotLicensedFault", targetNamespace = "http://portal.vidyo.com/superapi/")
public class NotLicensedFault_Exception extends Exception {
    
    private com.vidyo.portal.superapi.NotLicensedFault notLicensedFault;

    public NotLicensedFault_Exception() {
        super();
    }
    
    public NotLicensedFault_Exception(String message) {
        super(message);
    }
    
    public NotLicensedFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotLicensedFault_Exception(String message, com.vidyo.portal.superapi.NotLicensedFault notLicensedFault) {
        super(message);
        this.notLicensedFault = notLicensedFault;
    }

    public NotLicensedFault_Exception(String message, com.vidyo.portal.superapi.NotLicensedFault notLicensedFault, Throwable cause) {
        super(message, cause);
        this.notLicensedFault = notLicensedFault;
    }

    public com.vidyo.portal.superapi.NotLicensedFault getFaultInfo() {
        return this.notLicensedFault;
    }
}
