package com.vidyo.portal.superapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-04-21T14:11:45.695+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "VidyoPortalSuperService", 
                  wsdlLocation = "http://v.seekoom.com/services/VidyoPortalSuperService?wsdl",
                  targetNamespace = "http://portal.vidyo.com/superapi/") 
public class VidyoPortalSuperService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://portal.vidyo.com/superapi/", "VidyoPortalSuperService");
    public final static QName VidyoPortalSuperServicePort = new QName("http://portal.vidyo.com/superapi/", "VidyoPortalSuperServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://v.seekoom.com/services/VidyoPortalSuperService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VidyoPortalSuperService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://v.seekoom.com/services/VidyoPortalSuperService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VidyoPortalSuperService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VidyoPortalSuperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VidyoPortalSuperService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoPortalSuperService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoPortalSuperService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoPortalSuperService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns VidyoPortalSuperServicePortType
     */
    @WebEndpoint(name = "VidyoPortalSuperServicePort")
    public VidyoPortalSuperServicePortType getVidyoPortalSuperServicePort() {
        return super.getPort(VidyoPortalSuperServicePort, VidyoPortalSuperServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VidyoPortalSuperServicePortType
     */
    @WebEndpoint(name = "VidyoPortalSuperServicePort")
    public VidyoPortalSuperServicePortType getVidyoPortalSuperServicePort(WebServiceFeature... features) {
        return super.getPort(VidyoPortalSuperServicePort, VidyoPortalSuperServicePortType.class, features);
    }

}
