package com.vidyo.portal.superapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-04-21T14:11:45.384+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://portal.vidyo.com/superapi/", name = "VidyoPortalSuperServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VidyoPortalSuperServicePortType {

    /**
     * Retrieve the pool of routers.
     */
    @WebResult(name = "getRouterPoolListResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "getRouterPoolList")
    public GetRouterPoolListResponse getRouterPoolList(
        @WebParam(partName = "parameters", name = "getRouterPoolListRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        GetRouterPoolListRequest parameters
    ) throws GeneralFault_Exception;

    /**
     * Add and / or remove a list of allowed IPC domains. The user can add and remove IPC domains at the same time.
     */
    @WebResult(name = "setIpcDomainsResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "setIpcDomains")
    public SetIpcDomainsResponse setIpcDomains(
        @WebParam(partName = "parameters", name = "setIpcDomainsRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        SetIpcDomainsRequest parameters
    ) throws IncorrectIpcAccessLevelFault_Exception, GeneralFault_Exception;

    /**
     * Get the tenant details based on the tenant ID.
     */
    @WebResult(name = "GetTenantDetailsResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "getTenantDetails")
    public GetTenantDetailsResponse getTenantDetails(
        @WebParam(partName = "parameters", name = "GetTenantDetailsRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        GetTenantDetailsRequest parameters
    ) throws InvalidTenantFault_Exception, GeneralFault_Exception;

    /**
     * List all network components
     */
    @WebResult(name = "ListNetworkComponentsResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "listNetworkComponents")
    public ListNetworkComponentsResponse listNetworkComponents(
        @WebParam(partName = "parameters", name = "ListNetworkComponentsRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        ListNetworkComponentsRequest parameters
    ) throws GeneralFault_Exception;

    /**
     * Deleting an existing tenant from the system. The default tenant can not be deleted.
     */
    @WebResult(name = "DeleteTenantResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "deleteTenant")
    public DeleteTenantResponse deleteTenant(
        @WebParam(partName = "parameters", name = "DeleteTenantRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        DeleteTenantRequest parameters
    ) throws InvalidTenantFault_Exception, GeneralFault_Exception;

    /**
     * Provides the list of available service components. If the type is not specified, all lists will be provided. If the type is specified, only the list associated with this type will be provided
     */
    @WebResult(name = "GetServiceComponentsDataResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "getServiceComponentsData")
    public GetServiceComponentsDataResponse getServiceComponentsData(
        @WebParam(partName = "parameters", name = "GetServiceComponentsDataRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        GetServiceComponentsDataRequest parameters
    ) throws GeneralFault_Exception, InvalidArgumentFault_Exception;

    /**
     * Provides license data. If a tenant is not specified, the license parameters should be provided for all tenants as a Total number
     */
    @WebResult(name = "GetLicenseDataResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "getLicenseData")
    public GetLicenseDataResponse getLicenseData(
        @WebParam(partName = "parameters", name = "GetLicenseDataRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        GetLicenseDataRequest parameters
    ) throws NotAuthorizedFault_Exception, InvalidTenantFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception;

    /**
     * Save all tenant and user information about the entire system, and provides the saved backup file name.
     */
    @WebResult(name = "saveDBResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "saveDb")
    public SaveDBResponse saveDb(
        @WebParam(partName = "parameters", name = "saveDBRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        SaveDBRequest parameters
    ) throws GeneralFault_Exception;

    /**
     * Provide the level of access that user has to view and modify allowed IPC domains.
     */
    @WebResult(name = "getIpcAccessControlResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "getIpcAccessControl")
    public GetIpcAccessControlResponse getIpcAccessControl(
        @WebParam(partName = "parameters", name = "getIpcAccessControlRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        GetIpcAccessControlRequest parameters
    ) throws GeneralFault_Exception;

    /**
     * Update an existing tenant by the tenant ID. Each optional parameter that is provided aside from the tenant ID will overwrite the existing parameters.
     */
    @WebResult(name = "UpdateTenantResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "updateTenant")
    public UpdateTenantResponse updateTenant(
        @WebParam(partName = "parameters", name = "UpdateTenantRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        UpdateTenantRequest parameters
    ) throws InvalidTenantFault_Exception, GeneralFault_Exception, InvalidArgumentFault_Exception, ExistingTenantFault_Exception, NotLicensedFault_Exception;

    /**
     * Create a new tenant based on the information provided below.
     */
    @WebResult(name = "CreateTenantResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "createTenant")
    public CreateTenantResponse createTenant(
        @WebParam(partName = "parameters", name = "CreateTenantRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        CreateTenantRequest parameters
    ) throws GeneralFault_Exception, InvalidArgumentFault_Exception, ExistingTenantFault_Exception, NotLicensedFault_Exception;

    /**
     * Define IPC control access (Allow / Block) for Tenant and System levels.
     */
    @WebResult(name = "setIpcAccessControlResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "setIpcAccessControl")
    public SetIpcAccessControlResponse setIpcAccessControl(
        @WebParam(partName = "parameters", name = "setIpcAccessControlRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        SetIpcAccessControlRequest parameters
    ) throws GeneralFault_Exception, InvalidArgumentFault_Exception, MissingArgumentFault_Exception;

    /**
     * Get the list of all allowed or blocked IPC domains that are stored the database.
     */
    @WebResult(name = "getIpcDomainListResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "getIpcDomainList")
    public GetIpcDomainListResponse getIpcDomainList(
        @WebParam(partName = "parameters", name = "getIpcDomainListRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        GetIpcDomainListRequest parameters
    ) throws IncorrectIpcAccessLevelFault_Exception, GeneralFault_Exception;

    /**
     * Provide the location tags available on the portal.
     */
    @WebResult(name = "getLocationTagsResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "getLocationTags")
    public GetLocationTagsResponse getLocationTags(
        @WebParam(partName = "parameters", name = "getLocationTagsRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        GetLocationTagsRequest parameters
    ) throws GeneralFault_Exception;

    /**
     * Delete saved database backup from the disk.
     */
    @WebResult(name = "deleteDBResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "deleteDb")
    public DeleteDBResponse deleteDb(
        @WebParam(partName = "parameters", name = "deleteDBRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        DeleteDBRequest parameters
    ) throws GeneralFault_Exception, InvalidArgumentFault_Exception;

    /**
     * Provides the list of all tenants in the system with the following filters. All filters are optional and if a filter is not provided the query will use the defaults, which are sorting in a descending order all the tenants by the tenant names.
     */
    @WebResult(name = "ListTenantsResponse", targetNamespace = "http://portal.vidyo.com/superapi/", partName = "parameters")
    @WebMethod(action = "getListOfTenants")
    public ListTenantsResponse getListOfTenants(
        @WebParam(partName = "parameters", name = "ListTenantsRequest", targetNamespace = "http://portal.vidyo.com/superapi/")
        ListTenantsRequest parameters
    ) throws GeneralFault_Exception;
}
