
package com.vidyo.replay.apiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T14:59:40.449+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "AccessViolationFault", targetNamespace = "http://replay.vidyo.com/apiservice")
public class AccessViolationFault_Exception extends java.lang.Exception {
    
    private com.vidyo.replay.apiservice.AccessViolationFault accessViolationFault;

    public AccessViolationFault_Exception() {
        super();
    }
    
    public AccessViolationFault_Exception(String message) {
        super(message);
    }
    
    public AccessViolationFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AccessViolationFault_Exception(String message, com.vidyo.replay.apiservice.AccessViolationFault accessViolationFault) {
        super(message);
        this.accessViolationFault = accessViolationFault;
    }

    public AccessViolationFault_Exception(String message, com.vidyo.replay.apiservice.AccessViolationFault accessViolationFault, Throwable cause) {
        super(message, cause);
        this.accessViolationFault = accessViolationFault;
    }

    public com.vidyo.replay.apiservice.AccessViolationFault getFaultInfo() {
        return this.accessViolationFault;
    }
}
