
package com.vidyo.replay.apiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T14:59:40.444+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "GeneralFault", targetNamespace = "http://replay.vidyo.com/apiservice")
public class GeneralFault_Exception extends java.lang.Exception {
    
    private com.vidyo.replay.apiservice.GeneralFault generalFault;

    public GeneralFault_Exception() {
        super();
    }
    
    public GeneralFault_Exception(String message) {
        super(message);
    }
    
    public GeneralFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GeneralFault_Exception(String message, com.vidyo.replay.apiservice.GeneralFault generalFault) {
        super(message);
        this.generalFault = generalFault;
    }

    public GeneralFault_Exception(String message, com.vidyo.replay.apiservice.GeneralFault generalFault, Throwable cause) {
        super(message, cause);
        this.generalFault = generalFault;
    }

    public com.vidyo.replay.apiservice.GeneralFault getFaultInfo() {
        return this.generalFault;
    }
}
