package com.vidyo.replay.apiservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T14:59:40.454+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "VidyoReplayContentManagementService", 
                  wsdlLocation = "http://124.160.11.18/replay/services/VidyoReplayContentManagementService?wsdl",
                  targetNamespace = "http://replay.vidyo.com/apiservice") 
public class VidyoReplayContentManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://replay.vidyo.com/apiservice", "VidyoReplayContentManagementService");
    public final static QName VidyoReplayContentManagementServicePort = new QName("http://replay.vidyo.com/apiservice", "VidyoReplayContentManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://124.160.11.18/replay/services/VidyoReplayContentManagementService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VidyoReplayContentManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://124.160.11.18/replay/services/VidyoReplayContentManagementService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VidyoReplayContentManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VidyoReplayContentManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VidyoReplayContentManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoReplayContentManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoReplayContentManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoReplayContentManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns VidyoReplayContentManagementServicePortType
     */
    @WebEndpoint(name = "VidyoReplayContentManagementServicePort")
    public VidyoReplayContentManagementServicePortType getVidyoReplayContentManagementServicePort() {
        return super.getPort(VidyoReplayContentManagementServicePort, VidyoReplayContentManagementServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VidyoReplayContentManagementServicePortType
     */
    @WebEndpoint(name = "VidyoReplayContentManagementServicePort")
    public VidyoReplayContentManagementServicePortType getVidyoReplayContentManagementServicePort(WebServiceFeature... features) {
        return super.getPort(VidyoReplayContentManagementServicePort, VidyoReplayContentManagementServicePortType.class, features);
    }

}
