
package com.vidyo.portal.admin.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.956+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "GroupAlreadyExistsFault", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
public class GroupAlreadyExistsFault_Exception extends Exception {
    
    private com.vidyo.portal.admin.v1_1.GroupAlreadyExistsFault groupAlreadyExistsFault;

    public GroupAlreadyExistsFault_Exception() {
        super();
    }
    
    public GroupAlreadyExistsFault_Exception(String message) {
        super(message);
    }
    
    public GroupAlreadyExistsFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GroupAlreadyExistsFault_Exception(String message, com.vidyo.portal.admin.v1_1.GroupAlreadyExistsFault groupAlreadyExistsFault) {
        super(message);
        this.groupAlreadyExistsFault = groupAlreadyExistsFault;
    }

    public GroupAlreadyExistsFault_Exception(String message, com.vidyo.portal.admin.v1_1.GroupAlreadyExistsFault groupAlreadyExistsFault, Throwable cause) {
        super(message, cause);
        this.groupAlreadyExistsFault = groupAlreadyExistsFault;
    }

    public com.vidyo.portal.admin.v1_1.GroupAlreadyExistsFault getFaultInfo() {
        return this.groupAlreadyExistsFault;
    }
}
