
package com.vidyo.portal.admin.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.956+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "GroupNotFoundFault", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
public class GroupNotFoundFault_Exception extends Exception {
    
    private com.vidyo.portal.admin.v1_1.GroupNotFoundFault groupNotFoundFault;

    public GroupNotFoundFault_Exception() {
        super();
    }
    
    public GroupNotFoundFault_Exception(String message) {
        super(message);
    }
    
    public GroupNotFoundFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GroupNotFoundFault_Exception(String message, com.vidyo.portal.admin.v1_1.GroupNotFoundFault groupNotFoundFault) {
        super(message);
        this.groupNotFoundFault = groupNotFoundFault;
    }

    public GroupNotFoundFault_Exception(String message, com.vidyo.portal.admin.v1_1.GroupNotFoundFault groupNotFoundFault, Throwable cause) {
        super(message, cause);
        this.groupNotFoundFault = groupNotFoundFault;
    }

    public com.vidyo.portal.admin.v1_1.GroupNotFoundFault getFaultInfo() {
        return this.groupNotFoundFault;
    }
}
