
package com.vidyo.portal.admin.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.951+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "InvalidModeratorPINFormatFault", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
public class InvalidModeratorPINFormatFault_Exception extends Exception {
    
    private com.vidyo.portal.admin.v1_1.InvalidModeratorPINFormatFault invalidModeratorPINFormatFault;

    public InvalidModeratorPINFormatFault_Exception() {
        super();
    }
    
    public InvalidModeratorPINFormatFault_Exception(String message) {
        super(message);
    }
    
    public InvalidModeratorPINFormatFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidModeratorPINFormatFault_Exception(String message, com.vidyo.portal.admin.v1_1.InvalidModeratorPINFormatFault invalidModeratorPINFormatFault) {
        super(message);
        this.invalidModeratorPINFormatFault = invalidModeratorPINFormatFault;
    }

    public InvalidModeratorPINFormatFault_Exception(String message, com.vidyo.portal.admin.v1_1.InvalidModeratorPINFormatFault invalidModeratorPINFormatFault, Throwable cause) {
        super(message, cause);
        this.invalidModeratorPINFormatFault = invalidModeratorPINFormatFault;
    }

    public com.vidyo.portal.admin.v1_1.InvalidModeratorPINFormatFault getFaultInfo() {
        return this.invalidModeratorPINFormatFault;
    }
}
