
package com.vidyo.portal.admin.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.951+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "MemberAlreadyExistsFault", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
public class MemberAlreadyExistsFault_Exception extends Exception {
    
    private com.vidyo.portal.admin.v1_1.MemberAlreadyExistsFault memberAlreadyExistsFault;

    public MemberAlreadyExistsFault_Exception() {
        super();
    }
    
    public MemberAlreadyExistsFault_Exception(String message) {
        super(message);
    }
    
    public MemberAlreadyExistsFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MemberAlreadyExistsFault_Exception(String message, com.vidyo.portal.admin.v1_1.MemberAlreadyExistsFault memberAlreadyExistsFault) {
        super(message);
        this.memberAlreadyExistsFault = memberAlreadyExistsFault;
    }

    public MemberAlreadyExistsFault_Exception(String message, com.vidyo.portal.admin.v1_1.MemberAlreadyExistsFault memberAlreadyExistsFault, Throwable cause) {
        super(message, cause);
        this.memberAlreadyExistsFault = memberAlreadyExistsFault;
    }

    public com.vidyo.portal.admin.v1_1.MemberAlreadyExistsFault getFaultInfo() {
        return this.memberAlreadyExistsFault;
    }
}
