
package com.vidyo.portal.admin.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.941+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "MemberNotFoundFault", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
public class MemberNotFoundFault_Exception extends Exception {
    
    private com.vidyo.portal.admin.v1_1.MemberNotFoundFault memberNotFoundFault;

    public MemberNotFoundFault_Exception() {
        super();
    }
    
    public MemberNotFoundFault_Exception(String message) {
        super(message);
    }
    
    public MemberNotFoundFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MemberNotFoundFault_Exception(String message, com.vidyo.portal.admin.v1_1.MemberNotFoundFault memberNotFoundFault) {
        super(message);
        this.memberNotFoundFault = memberNotFoundFault;
    }

    public MemberNotFoundFault_Exception(String message, com.vidyo.portal.admin.v1_1.MemberNotFoundFault memberNotFoundFault, Throwable cause) {
        super(message, cause);
        this.memberNotFoundFault = memberNotFoundFault;
    }

    public com.vidyo.portal.admin.v1_1.MemberNotFoundFault getFaultInfo() {
        return this.memberNotFoundFault;
    }
}
