
package com.vidyo.portal.admin.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.946+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "RoomNotFoundFault", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
public class RoomNotFoundFault_Exception extends Exception {
    
    private com.vidyo.portal.admin.v1_1.RoomNotFoundFault roomNotFoundFault;

    public RoomNotFoundFault_Exception() {
        super();
    }
    
    public RoomNotFoundFault_Exception(String message) {
        super(message);
    }
    
    public RoomNotFoundFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RoomNotFoundFault_Exception(String message, com.vidyo.portal.admin.v1_1.RoomNotFoundFault roomNotFoundFault) {
        super(message);
        this.roomNotFoundFault = roomNotFoundFault;
    }

    public RoomNotFoundFault_Exception(String message, com.vidyo.portal.admin.v1_1.RoomNotFoundFault roomNotFoundFault, Throwable cause) {
        super(message, cause);
        this.roomNotFoundFault = roomNotFoundFault;
    }

    public com.vidyo.portal.admin.v1_1.RoomNotFoundFault getFaultInfo() {
        return this.roomNotFoundFault;
    }
}
