
package com.vidyo.portal.admin.v1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.951+08:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "RoomAlreadyExistsFault", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
public class RoomAlreadyExistsFault_Exception extends Exception {
    
    private com.vidyo.portal.admin.v1_1.RoomAlreadyExistsFault roomAlreadyExistsFault;

    public RoomAlreadyExistsFault_Exception() {
        super();
    }
    
    public RoomAlreadyExistsFault_Exception(String message) {
        super(message);
    }
    
    public RoomAlreadyExistsFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RoomAlreadyExistsFault_Exception(String message, com.vidyo.portal.admin.v1_1.RoomAlreadyExistsFault roomAlreadyExistsFault) {
        super(message);
        this.roomAlreadyExistsFault = roomAlreadyExistsFault;
    }

    public RoomAlreadyExistsFault_Exception(String message, com.vidyo.portal.admin.v1_1.RoomAlreadyExistsFault roomAlreadyExistsFault, Throwable cause) {
        super(message, cause);
        this.roomAlreadyExistsFault = roomAlreadyExistsFault;
    }

    public com.vidyo.portal.admin.v1_1.RoomAlreadyExistsFault getFaultInfo() {
        return this.roomAlreadyExistsFault;
    }
}
