package com.vidyo.portal.admin.v1_1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.966+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "VidyoPortalAdminService", 
                  wsdlLocation = "http://210.14.78.26/services/v1_1/VidyoPortalAdminService?wsdl",
                  targetNamespace = "http://portal.vidyo.com/admin/v1_1") 
public class VidyoPortalAdminService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://portal.vidyo.com/admin/v1_1", "VidyoPortalAdminService");
    public final static QName VidyoPortalAdminServicePort = new QName("http://portal.vidyo.com/admin/v1_1", "VidyoPortalAdminServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://210.14.78.26/services/v1_1/VidyoPortalAdminService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VidyoPortalAdminService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://210.14.78.26/services/v1_1/VidyoPortalAdminService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VidyoPortalAdminService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VidyoPortalAdminService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VidyoPortalAdminService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoPortalAdminService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoPortalAdminService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public VidyoPortalAdminService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns VidyoPortalAdminServicePortType
     */
    @WebEndpoint(name = "VidyoPortalAdminServicePort")
    public VidyoPortalAdminServicePortType getVidyoPortalAdminServicePort() {
        return super.getPort(VidyoPortalAdminServicePort, VidyoPortalAdminServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VidyoPortalAdminServicePortType
     */
    @WebEndpoint(name = "VidyoPortalAdminServicePort")
    public VidyoPortalAdminServicePortType getVidyoPortalAdminServicePort(WebServiceFeature... features) {
        return super.getPort(VidyoPortalAdminServicePort, VidyoPortalAdminServicePortType.class, features);
    }

}
