package com.vidyo.portal.admin.v1_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-05T17:32:26.961+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://portal.vidyo.com/admin/v1_1", name = "VidyoPortalAdminServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VidyoPortalAdminServicePortType {

    @WebResult(name = "RemoveWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "removeWebcastURL")
    public RemoveWebcastURLResponse removeWebcastURL(
        @WebParam(partName = "parameter", name = "RemoveWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        RemoveWebcastURLRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetGroupsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getGroups")
    public GetGroupsResponse getGroups(
        @WebParam(partName = "parameter", name = "GetGroupsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetGroupsRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "DeleteMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "deleteMember")
    public DeleteMemberResponse deleteMember(
        @WebParam(partName = "parameter", name = "DeleteMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        DeleteMemberRequest parameter
    ) throws MemberNotFoundFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getRoom")
    public GetRoomResponse getRoom(
        @WebParam(partName = "parameter", name = "GetRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetRoomRequest parameter
    ) throws RoomNotFoundFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "UpdateMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "updateMember")
    public UpdateMemberResponse updateMember(
        @WebParam(partName = "parameter", name = "UpdateMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        UpdateMemberRequest parameter
    ) throws MemberNotFoundFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "DeleteRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "deleteRoom")
    public DeleteRoomResponse deleteRoom(
        @WebParam(partName = "parameter", name = "DeleteRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        DeleteRoomRequest parameter
    ) throws RoomNotFoundFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "StartRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "startRecording")
    public StartRecordingResponse startRecording(
        @WebParam(partName = "parameter", name = "StartRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        StartRecordingRequest parameter
    ) throws ResourceNotAvailableFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "CreateWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "createWebcastURL")
    public CreateWebcastURLResponse createWebcastURL(
        @WebParam(partName = "parameter", name = "CreateWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        CreateWebcastURLRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getRoomProfile")
    public GetRoomProfileResponse getRoomProfile(
        @WebParam(partName = "parameter", name = "GetRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetRoomProfileRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "RemoveRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "removeRoomProfile")
    public RemoveRoomProfileResponse removeRoomProfile(
        @WebParam(partName = "parameter", name = "RemoveRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        RemoveRoomProfileRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "SetRoomProfileResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "setRoomProfile")
    public SetRoomProfileResponse setRoomProfile(
        @WebParam(partName = "parameter", name = "SetRoomProfileRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        SetRoomProfileRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetWebcastURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getWebcastURL")
    public GetWebcastURLResponse getWebcastURL(
        @WebParam(partName = "parameter", name = "GetWebcastURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetWebcastURLRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "LeaveConferenceResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "leaveConference")
    public LeaveConferenceResponse leaveConference(
        @WebParam(partName = "parameter", name = "LeaveConferenceRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        LeaveConferenceRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "StopRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "stopRecording")
    public StopRecordingResponse stopRecording(
        @WebParam(partName = "parameter", name = "StopRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        StopRecordingRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "RemoveModeratorPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "removeRoomModeratorPIN")
    public RemoveModeratorPINResponse removeModeratorPIN(
        @WebParam(partName = "parameter", name = "RemoveModeratorPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        RemoveModeratorPINRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetLocationTagsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getLocationTags")
    public GetLocationTagsResponse getLocationTags(
        @WebParam(partName = "parameter", name = "GetLocationTagsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetLocationTagsRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetParticipantsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getParticipants")
    public GetParticipantsResponse getParticipants(
        @WebParam(partName = "parameter", name = "GetParticipantsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetParticipantsRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "UpdateRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "updateRoom")
    public UpdateRoomResponse updateRoom(
        @WebParam(partName = "parameter", name = "UpdateRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        UpdateRoomRequest parameter
    ) throws RoomNotFoundFault_Exception, RoomAlreadyExistsFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "CreateWebcastPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "createWebcastPIN")
    public CreateWebcastPINResponse createWebcastPIN(
        @WebParam(partName = "parameter", name = "CreateWebcastPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        CreateWebcastPINRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getMember")
    public GetMemberResponse getMember(
        @WebParam(partName = "parameter", name = "GetMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetMemberRequest parameter
    ) throws MemberNotFoundFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "InviteToConferenceResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "inviteToConference")
    public InviteToConferenceResponse inviteToConference(
        @WebParam(partName = "parameter", name = "InviteToConferenceRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        InviteToConferenceRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "CreateRoomPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "createRoomPIN")
    public CreateRoomPINResponse createRoomPIN(
        @WebParam(partName = "parameter", name = "CreateRoomPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        CreateRoomPINRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetPortalVersionResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getPortalVersion")
    public GetPortalVersionResponse getPortalVersion(
        @WebParam(partName = "parameter", name = "GetPortalVersionRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        java.lang.Object parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetRoomsResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getRooms")
    public GetRoomsResponse getRooms(
        @WebParam(partName = "parameter", name = "GetRoomsRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetRoomsRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetRoomProfilesResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getRoomProfiles")
    public GetRoomProfilesResponse getRoomProfiles(
        @WebParam(partName = "parameter", name = "GetRoomProfilesRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        java.lang.Object parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "CreateModeratorPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "createRoomModeratorPIN")
    public CreateModeratorPINResponse createModeratorPIN(
        @WebParam(partName = "parameter", name = "CreateModeratorPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        CreateModeratorPINRequest parameter
    ) throws InvalidModeratorPINFormatFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "RemoveWebcastPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "removeWebcastPIN")
    public RemoveWebcastPINResponse removeWebcastPIN(
        @WebParam(partName = "parameter", name = "RemoveWebcastPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        RemoveWebcastPINRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "CreateRoomURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "createRoomURL")
    public CreateRoomURLResponse createRoomURL(
        @WebParam(partName = "parameter", name = "CreateRoomURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        CreateRoomURLRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "RemoveRoomURLResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "removeRoomURL")
    public RemoveRoomURLResponse removeRoomURL(
        @WebParam(partName = "parameter", name = "RemoveRoomURLRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        RemoveRoomURLRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetLicenseDataResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getLicenseData")
    public GetLicenseDataResponse getLicenseData(
        @WebParam(partName = "parameter", name = "GetLicenseDataRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetLicenseDataRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "UnmuteAudioResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "unmuteAudio")
    public UnmuteAudioResponse unmuteAudio(
        @WebParam(partName = "parameter", name = "UnmuteAudioRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        UnmuteAudioRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetRecordingProfilesResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getRecordingProfiles")
    public GetRecordingProfilesResponse getRecordingProfiles(
        @WebParam(partName = "parameter", name = "GetRecordingProfilesRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        java.lang.Object parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "AddMemberResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "addMember")
    public AddMemberResponse addMember(
        @WebParam(partName = "parameter", name = "AddMemberRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        AddMemberRequest parameter
    ) throws MemberAlreadyExistsFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "ResumeRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "resumeRecording")
    public ResumeRecordingResponse resumeRecording(
        @WebParam(partName = "parameter", name = "ResumeRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        ResumeRecordingRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "StartVideoResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "startVideo")
    public StartVideoResponse startVideo(
        @WebParam(partName = "parameter", name = "StartVideoRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        StartVideoRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "DeleteGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "deleteGroup")
    public DeleteGroupResponse deleteGroup(
        @WebParam(partName = "parameter", name = "DeleteGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        DeleteGroupRequest parameter
    ) throws GroupNotFoundFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "PauseRecordingResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "pauseRecording")
    public PauseRecordingResponse pauseRecording(
        @WebParam(partName = "parameter", name = "PauseRecordingRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        PauseRecordingRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "MuteAudioResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "muteAudio")
    public MuteAudioResponse muteAudio(
        @WebParam(partName = "parameter", name = "MuteAudioRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        MuteAudioRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getGroup")
    public GetGroupResponse getGroup(
        @WebParam(partName = "parameter", name = "GetGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetGroupRequest parameter
    ) throws GroupNotFoundFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "GetMembersResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "getMembers")
    public GetMembersResponse getMembers(
        @WebParam(partName = "parameter", name = "GetMembersRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        GetMembersRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "RemoveRoomPINResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "removeRoomPIN")
    public RemoveRoomPINResponse removeRoomPIN(
        @WebParam(partName = "parameter", name = "RemoveRoomPINRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        RemoveRoomPINRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "UpdateGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "updateGroup")
    public UpdateGroupResponse updateGroup(
        @WebParam(partName = "parameter", name = "UpdateGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        UpdateGroupRequest parameter
    ) throws GroupNotFoundFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "AddGroupResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "addGroup")
    public AddGroupResponse addGroup(
        @WebParam(partName = "parameter", name = "AddGroupRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        AddGroupRequest parameter
    ) throws GroupAlreadyExistsFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "AddRoomResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "addRoom")
    public AddRoomResponse addRoom(
        @WebParam(partName = "parameter", name = "AddRoomRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        AddRoomRequest parameter
    ) throws RoomAlreadyExistsFault_Exception, GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;

    @WebResult(name = "StopVideoResponse", targetNamespace = "http://portal.vidyo.com/admin/v1_1", partName = "parameter")
    @WebMethod(action = "stopVideo")
    public StopVideoResponse stopVideo(
        @WebParam(partName = "parameter", name = "StopVideoRequest", targetNamespace = "http://portal.vidyo.com/admin/v1_1")
        StopVideoRequest parameter
    ) throws GeneralFault_Exception, NotLicensedFault_Exception, InvalidArgumentFault_Exception;
}
